##
## config/application_settings.yml
##
##
default: &default
  github:
    organization: XXXXXX
  oauth:
    github:
      client_id: XXXXXXXXXXXXXXXXX
      client_secret: XXXXXXXXXXXXXXXXXXX
      ## allowed_team_id is a github team id adllowed to login.
      ## It can be checked by:
      ##   curl -u [your-github-account] https://api.github.com/orgs/:org/teams
      allowed_team_id: xxxxx
  webhook:
    clients:
      - url: https://example.com
        content-type: application/json
        events:
          - create
          - update
          - destroy

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
